title:              Archin's Blog
email:              th_kim@pusan.ac.kr
description:        Archin's Blog
author:             Archin
# baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://archin-coding.github.io/"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    Archin-coding
facebook_username:  kim.ktaehyeong
instagram_username:  archin2
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
