# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Archin's Blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Archin's Blog

description: Stylish Jekyll Theme
author:
  name: Archin
  email: th_kim@pusan.ac.kr
  github: Archin-coding
  # twitter: 
  # pinterest: 
  # linkedin: 
  bio: 수학, 코딩을 잘 하고 싶은 사람입니다.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image

# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
